# .goreleaser.yml
#
# A specific config for homebrew releases that cannot be run as a GitHub Action.
#
# Instructions:
# 1) Push all changes to the bengarrett/dupers.
# 2) On GitHub publish a new release tag and let the GitHub Action finish.
# 3) In a local terminal do the following:
#
# cd github/retrotxtgo
# git pull
# export GITHUB_TOKEN="YOUR_GH_TOKEN"
# goreleaser release --skip-validate --rm-dist --config .brew/.goreleaser.yml
#
# To test the config:
# goreleaser check
# goreleaser release --clean --snapshot
project_name: dupers
before:
  hooks:
    - go mod tidy
builds:
  - id: Linux
    goos: ['linux']
    goarch: ['amd64', 'arm64']
    dir: ../
  - id: macOS
    goos: ['darwin']
    goarch: ['amd64', 'arm64']
    dir: ../
release:
  github:
    owner: bengarrett
    name: homebrew-dupers
brews:
  - tap:
      owner: bengarrett
      name: homebrew-tap
    folder: Formula
    goarm: "7"
    homepage: "https://github.com/bengarrett/dupers"
    description: "The blazing-fast file duplicate checker and filename search."
    license: "LGPL 3.0"
    test: |-
      system "#{bin}/dupers --version"
    install: |-
      bin.install "dupers"