linters:
  enable-all: true
  disable:
    - interfacer
    - scopelint
    - golint
    - maligned
    - nlreturn
    - tagliatelle
    - testpackage
    - wrapcheck

    - paralleltest
    - exhaustivestruct

linters-settings:
  cyclop:
    # the maximal code complexity to report
    max-complexity: 15