version: "2"
linters:
  default: all
  disable:
    - depguard
    - exhaustruct
    - nlreturn
    - noinlineerr
    - varnamelen
    - wsl
    - wsl_v5
  exclusions:
    rules:
      - linters:
          - dupl
          - lll
          - varnamelen
        path: _test\.go
  settings:
    cyclop:
      max-complexity: 15
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
