version: '2'
linters:
  default: all
  disable:
    - depguard
    - exhaustruct
    - gomodguard
    - nlreturn
    - noinlineerr
    - paralleltest
    - revive # false positives?
    - varnamelen
    - wrapcheck
    - wsl
    - wsl_v5
  exclusions:
    rules:
      - linters:
          - cyclop
          - dupl
          - errcheck
          - funlen
          - gocognit
          - goconst
          - lll
          - varnamelen
        path: _test\.go
      - linters:
          - goconst
        path: _fuzz\.go
  settings:
    cyclop:
      max-complexity: 15
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
