# golangci-lint run
# gofumpt -l -w .
# gci -w .
# go test -timeout 30s -coverprofile=/tmp/vscode-gohSFtcj/go-code-cover ./...

linters:
  enable-all: true
  fast: true
  disable:
    # deprecated
    # opinionated
    - depguard
    - nlreturn
    - paralleltest
    - varnamelen
    - wsl