linters:
  enable-all: true
  disable:
    - interfacer
    - scopelint
    - golint
    - maligned
    - nlreturn
    - tagliatelle
    - testpackage
    - wrapcheck

    - paralleltest # breaks tests
    - exhaustivestruct
    - forbidigo
    - wsl

linters-settings:
  cyclop:
    # the maximal code complexity to report
    max-complexity: 15