# .goreleaser.yml
#
# test the config:
# goreleaser check
# goreleaser release --skip-publish --skip-validate --rm-dist

before:
  hooks:
    - go mod tidy
builds:
  - id: FreeBSD
    goos: ['freebsd']
    goarch: ['amd64']
  - id: Linux Intel
    goos: ['linux']
    goarch: ['amd64']
  - id: macOS
    goos: ['darwin']
    goarch: ['amd64', 'arm64']
  - id: Windows
    goos: ['windows']
    goarch: ['386', 'amd64']

archives:
  - id: FreeBSD
    builds: ['FreeBSD']
    format: tar.gz
    files:
    - none*
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      amd64: Intel
      freebsd: FreeBSD
  - id: Linux Intel
    builds: ['Linux Intel']
    format: tar.gz
    files:
    - none*
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      amd64: Intel
      linux: Linux
  - id: macOS
    builds: ['macOS']
    format: tar.gz
    files:
    - none*
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      arm64: M-series
      amd64: Intel
      darwin: macOS
  - id: Windows
    builds: ['Windows']
    format: zip
    files:
    - none*
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      386: 32bit
      amd64: Intel
      windows: Windows

nfpms:
  - id: Linux
    builds: ['Linux Intel']
    file_name_template: "{{ .ProjectName }}"
    replacements:
      amd64: Intel
      linux: Linux
    vendor: Ben Garrett.
    homepage: https://github.com/bengarrett/dupers
    maintainer: Ben Garrett <code.by.ben@gmail.com>
    description: The blazing-fast file duplicate checker and filename search.
    license: LGPL 3.0
    formats:
      - apk
      - deb
      - rpm

scoop:
  bucket:
    owner: bengarrett
    name: dupers

  commit_author:
    name: goreleaserbot
    email: goreleaser@carlosbecker.com

  commit_msg_template: "Scoop update for {{ .ProjectName }} version {{ .Tag }}"

  homepage: "https://github.com/bengarrett/dupers/"

  description: "A batch viewer and extractor for large collections of zip archives."

  license: LGPL 3.0

  # Setting this will prevent goreleaser to actually try to commit the updated
  # manifest leaving the responsibility of publishing it to the user.
  # If set to auto, the release will not be uploaded to the scoop bucket
  # in case there is an indicator for prerelease in the tag e.g. v1.0.0-rc1
  # Default is false.
  skip_upload: auto