# .goreleaser.yml
#
# To test this GoReleaser configuration:
# goreleaser check
# goreleaser release --clean --snapshot
version: 2
project_name: dupers
before:
  hooks:
    - go mod tidy
builds:
  - id: Linux
    goos: ['linux']
    goarch: ['amd64', 'arm64']
  - id: macOS
    goos: ['darwin']
    goarch: ['amd64', 'arm64']
  - id: Windows
    goos: ['windows']
    goarch: ['amd64', '386']
universal_binaries:
  - id: macOS
    name_template: "{{ .ProjectName }}"
    replace: true

archives:
  - name_template: '{{ .ProjectName }}_{{ if eq .Os "darwin" }}macos{{ else }}{{ tolower .Os }}_{{ tolower .Arch }}{{ end }}'
    files:
    - src: internal/logo.txt
      strip_parent: true
    format_overrides:
      - goos: windows
        format: zip

nfpms:
  - file_name_template: "{{ .ProjectName }}_{{ tolower .Arch }}"
    vendor: Ben Garrett.
    homepage: https://github.com/bengarrett/dupers
    maintainer: Ben Garrett <code.by.ben@gmail.com>
    description: The blazing-fast file duplicate checker and filename search.
    license: LGPL 3.0
    section: utils
    formats:
      - apk
      - deb
      - rpm
      - archlinux

changelog:
  sort: asc
  use: git
  filters:
    exclude:
    - '^test:'
    - '^chore'
    - 'merge conflict'
    - Merge pull request
    - Merge remote-tracking branch
    - Merge branch
    - go mod tidy