# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  race:
    silent: true
    cmds:
      - go build -v -race -o dupers main.go
  args:
    silent: true
    cmds:
      - echo -e "## Testing help.\n"
      - go run -race main.go
      - echo -e "## Testing -mono.\n"
      - go run -race main.go -mono
      - echo -e "## Testing database help"
      - go run -race main.go -h database
      - echo -e "## Testing search help"
      - go run -race main.go search --help
      - echo -e "## Testing dupe help"
      - go run -race main.go -help dupe
      - echo -e "## Testing -version.\n"
      - go run -race main.go -version
      - echo -e "## Testing -mono -version.\n"
      - go run -race main.go -mono -version      
      - echo -e "## Testing -mono -version -quiet.\n"
      - go run -race main.go -mono -version -quiet
      - echo -e "## Testing -mvq.\n"
      - go run -race main.go -m -v -q
      - echo -e "## Database"
      - go run -race main.go database
      - echo -e "## DB -d -m"
      - go run -race main.go db -d -m
      - echo -e "## Debug aliases"
      - go run -race main.go -m -q -d -v -h -e -n -f
      - echo -e "## Debug flag"
      - go run -race main.go -mono -quiet -debug -version -help -exact -name -fast -delete -delete+ -sensen