name: GoReleaser

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
  
permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Git fetch
        run: git fetch --force --tags
      - name: Setup Go with cache
        uses: actions/setup-go@v5
      - name: GoReleaser run
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
