name: GoReleaser

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Git fetch
        run: git fetch --force --tags
      - name: Setup Go with cache
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.20.0'
          cache: true
      - name: GoReleaser run
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
